INSERT INTO stars(Course, Star, PageName)
VALUES
(1,1,'Big Bob-omb on the Summit'),
(1,2,'Footrace with Koopa the Quick'),
(1,3,'Shoot to the Island in the Sky'),
(1,4,'Find the 8 Red Coins'),
(1,5,'Mario Wings to the Sky'),
(1,6,'Behind Chain Chomp''s Gate'),
(1,7,'BoB 100 Coins'),
(2,1,'Chip off Whomp''s Block'),
(2,2,'To the Top of the Fortress'),
(2,3,'Shoot into the Wild Blue'),
(2,4,'Red Coins on the Floating Isle'),
(2,5,'Fall onto the Caged Island'),
(2,6,'Blast Away the Wall'),
(2,7,'WF 100 Coins'),
(3,1,'Plunder in the Sunken Ship'),
(3,2,'Can the Eel Come out to Play?'),
(3,3,'Treasure of the Ocean Cave'),
(3,4,'Red Coins on the Ship Afloat'),
(3,5,'Blast to the Stone Pillar'),
(3,6,'Through the Jet Stream'),
(3,7,'JRB 100 Coins'),
(4,1,'Slip Slidin'' Away'),
(4,2,'Li''l Penguin Lost'),
(4,3,'Big Penguin Race'),
(4,4,'Frosty Slide for 8 Red Coins'),
(4,5,'Snowman''s Lost His Head'),
(4,6,'Wall Kicks Will Work'),
(4,7,'CCM 100 Coins'),
(5,1,'Go on a Ghost Hunt'),
(5,2,'Ride Big Boo''s Merry-Go-Round'),
(5,3,'Secret of the Haunted Books'),
(5,4,'Seek the 8 Red Coins'),
(5,5,'Big Boo''s Balcony'),
(5,6,'Eye to Eye in the Secret Room'),
(5,7,'BBH 100 Coins'),
(6,1,'Swimming Beast in the Cavern'),
(6,2,'Elevate for 8 Red Coins'),
(6,3,'Metal-Head Mario Can Move!'),
(6,4,'Navigating the Toxic Maze'),
(6,5,'A-Maze-ing Emergency Exit'),
(6,6,'Watch for Rolling Rocks'),
(6,7,'HMC 100 Coins'),
(7,1,'Boil the Big Bully'),
(7,2,'Bully the Bullies'),
(7,3,'8-Coin Puzzle with 15 Pieces'),
(7,4,'Red-Hot Log Rolling'),
(7,5,'Hot-Foot-It into the Volcano'),
(7,6,'Elevator Tour in the Volcano'),
(7,7,'LLL 100 Coins'),
(8,1,'In the Talons of the Big Bird'),
(8,2,'Shining Atop the Pyramid'),
(8,3,'Inside the Ancient Pyramid'),
(8,4,'Stand Tall on the Four Pillars'),
(8,5,'Free Flying for 8 Red Coins'),
(8,6,'Pyramid Puzzle'),
(8,7,'SSL 100 Coins'),
(9,1,'Board Bowser''s Sub'),
(9,2,'Chests in the Current'),
(9,3,'Pole-Jumping for Red Coins'),
(9,4,'Through the Jet Stream'),
(9,5,'The Manta Ray''s Reward'),
(9,6,'Collect the Caps...'),
(9,7,'DDD 100 Coins'),
(10,1,'Snowman''s Big Head'),
(10,2,'Chill with the Bully'),
(10,3,'In the Deep Freeze'),
(10,4,'Whirl from the Freezing Pond'),
(10,5,'Shell Shreddin'' for Red Coins'),
(10,6,'Into the Igloo'),
(10,7,'SL 100 Coins'),
(11,1,'Shocking Arrow Lifts!'),
(11,2,'Top o'' the Town'),
(11,3,'Secrets in the Shallows & Sky'),
(11,4,'Express Elevator--Hurry Up!'),
(11,5,'Go to Town for Red Coins'),
(11,6,'Quick Race Through Downtown!'),
(11,7,'WDW 100 Coins: With Secrets / With Reds'),
(12,1,'Scale the Mountain'),
(12,2,'Mystery of the Monkey Cage'),
(12,3,'Scary ''Shrooms, Red Coins'),
(12,4,'Mysterious Mountainside'),
(12,5,'Breathtaking View from Bridge'),
(12,6,'Blast to the Lonely Mushroom'),
(12,7,'TTM 100 Coins'),
(13,1,'Pluck the Piranha Flower'),
(13,2,'The Tip Top of the Huge Island'),
(13,3,'Rematch with Koopa the Quick'),
(13,4,'Five Itty Bitty Secrets'),
(13,5,'Wiggler''s Red Coins'),
(13,6,'Make Wiggler Squirm'),
(13,7,'THI 100 Coins'),
(14,1,'Roll into the Cage'),
(14,2,'The Pit and the Pendulums'),
(14,3,'Get a Hand'),
(14,4,'Stomp on the Thwomp'),
(14,5,'Timed Jumps on Moving Bars'),
(14,6,'Stop Time for Red Coins'),
(14,7,'TTC 100 Coins'),
(15,1,'Cruiser Crossing the Rainbow'),
(15,2,'The Big House in the Sky'),
(15,3,'Coins Amassed in a Maze'),
(15,4,'Swingin'' in the Breeze'),
(15,5,'Tricky Triangles!'),
(15,6,'Somewhere Over the Rainbow'),
(15,7,'RR 100 Coins'),
(16,0,'Bowser in the Dark World'),
(16,1,'Bowser in the Dark World'),
(16,2,'Bowser in the Dark World'),
(17,0,'Bowser in the Fire Sea'),
(17,1,'Bowser in the Fire Sea'),
(17,2,'Bowser in the Fire Sea'),
(18,0,'Bowser in the Sky'),
(18,1,'Bowser in the Sky'),
(18,2,'Bowser in the Sky'),
(19,1,'The Princess''s Secret Slide'),
(19,2,'The Princess''s Secret Slide'),
(20,1,'Cavern of the Metal Cap'),
(21,1,'Tower of the Wing Cap'),
(22,1,'Vanish Cap Under the Moat'),
(23,1,'Wing Mario Over the Rainbow'),
(24,1,'The Secret Aquarium');